Repository State-of-Rhode-Island-eCMS/ecms_patternlab, pull requests merged in 2020-11, with the labels that each got.

#25 Prepare the changelog for 0.1.6
  CHANGELOG.md
Labels: approved, release

#27 Prepare changelog for 0.1.7
  CHANGELOG.md
Labels: release

#28 Removed t function from media item twig
  CHANGELOG.md
  source/_patterns/01-molecules/media-item/media-item.twig
Labels: twig

#29 Nav current updates, Sidebar nav theming, Promo teasers, Social updates
  dist/css/pattern-lab-compiled.css
  dist/js/pattern-lab-compiled-min.js
  dist/js/pattern-lab-compiled.js
  source/_data/color-config.hjson
  source/_data/color-config.json
  source/_data/colors-generated.json
  source/_patterns/00-atoms/00-base/__breakpoints.scss
  source/_patterns/01-molecules/media-item/_media_item.scss
  source/_patterns/01-molecules/site-search/site-search.twig
  source/_patterns/01-molecules/teaser-promotion/_teaser-promotion.scss
  source/_patterns/01-molecules/teaser-promotion/teaser-promotion.json
  source/_patterns/01-molecules/teaser-promotion/teaser-promotion.twig
  source/_patterns/02-organisms/navigation-main/_navigation-main.scss
  source/_patterns/02-organisms/navigation-main/navigation-main.js
  source/_patterns/02-organisms/navigation-main/navigation-main.json
  source/_patterns/02-organisms/navigation-main/navigation-main.twig
  source/_patterns/02-organisms/navigation-minor/_navigation-minor.scss
  source/_patterns/02-organisms/navigation-minor/navigation-minor.js
  source/_patterns/02-organisms/navigation-minor/navigation-minor.json
  source/_patterns/02-organisms/navigation-minor/navigation-minor.twig
  source/_patterns/03-templates/00-layouts/_page.scss
  source/_patterns/04-pages/navigation-demo.json
  source/_patterns/04-pages/navigation-demo.twig
Labels: js, scss, twig

#34 Prepare changelog for 0.1.10 release
  CHANGELOG.md
Labels: release

#36 Prepare changelog for 0.2.1
  CHANGELOG.md
Labels: release

#38 Prepare changelog for 0.2.2.
  CHANGELOG.md
Labels: release

#41 Bug Bash work, IE11, Clamp changes, Copyright text
  CHANGELOG.md
  dist/css/pattern-lab-compiled.css
  dist/js/pattern-lab-compiled-min.js
  dist/js/pattern-lab-compiled.js
  source/_data/color-config.hjson
  source/_data/color-config.json
  source/_patterns/00-atoms/00-base/__breakpoints.scss
  source/_patterns/00-atoms/00-base/__variables.scss
  source/_patterns/00-atoms/02-text/_00-typography.scss
  source/_patterns/00-atoms/05-forms/_00-forms.scss
  source/_patterns/00-atoms/07-tables/_00-table.scss
  source/_patterns/01-molecules/teaser-notification/_teaser-notification.scss
  source/_patterns/01-molecules/teaser-notification/teaser-notification.twig
  source/_patterns/01-molecules/teaser-promotion/_teaser-promotion.scss
  source/_patterns/01-molecules/user-settings/user-settings.js
  source/_patterns/01-molecules/watson-chat/watson-chat.twig
  source/_patterns/02-organisms/navigation-main/_navigation-main.scss
  source/_patterns/02-organisms/navigation-main/navigation-main.js
  source/_patterns/02-organisms/navigation-minor/_navigation-minor.scss
  source/_patterns/02-organisms/navigation-minor/navigation-minor.js
  source/_patterns/02-organisms/notfications-block/_notifications-block.scss
  source/_patterns/02-organisms/notfications-block/notifications-block.js
  source/_patterns/02-organisms/page-footer/page-footer.json
  source/_patterns/02-organisms/page-footer/page-footer.twig
  source/_patterns/03-templates/00-layouts/_page.scss
  source/_patterns/03-templates/00-layouts/html.html.pl.twig
  source/_patterns/03-templates/00-layouts/page--landing-page.html.pl.twig
  source/_patterns/03-templates/00-layouts/page.html.pl.twig
  source/js/global.js
Labels: js, scss, twig

#42 Prepare CHANGELOG for release 0.2.4
  CHANGELOG.md
Labels: approved

#43 Promo style changes, notifications style updates, sidebar width changes
  dist/css/pattern-lab-compiled.css
  dist/js/pattern-lab-compiled-min.js
  dist/js/pattern-lab-compiled.js
  source/_patterns/01-molecules/media-item/media-item.twig
  source/_patterns/01-molecules/teaser-notification/teaser-notification.twig
  source/_patterns/01-molecules/teaser-promotion/_teaser-promotion.scss
  source/_patterns/02-organisms/navigation-minor/_navigation-minor.scss
  source/_patterns/02-organisms/notfications-block/_notifications-block.scss
  source/_patterns/03-templates/00-layouts/_page.scss
Labels: approved, scss, twig

#44 Prepare changelog for 0.2.5 release
  CHANGELOG.md
Labels: release

#45 Theme site search
  CHANGELOG.md
  source/_patterns/00-atoms/05-forms/search-submit.twig
  source/_patterns/01-molecules/site-search/_site-search.scss
  source/_patterns/01-molecules/site-search/site-search--inner.twig
  source/_patterns/01-molecules/site-search/site-search.twig
  source/_patterns/01-molecules/teaser-article/teaser-article.twig
  source/_patterns/02-organisms/page-header/_page-header.scss
  source/_patterns/02-organisms/page-header/page-header.twig
Labels: scss, twig

#46 Bug fixes, Text cards, Forms, Page Title with Image
  CHANGELOG.md
  dist/css/pattern-lab-compiled.css
  dist/js/pattern-lab-compiled-min.js
  dist/js/pattern-lab-compiled.js
  source/_data/color-config.hjson
  source/_data/color-config.json
  source/_data/colors-generated.json
  source/_patterns/00-atoms/00-base/__breakpoints.scss
  source/_patterns/00-atoms/00-base/__variables.scss
  source/_patterns/00-atoms/02-text/_00-typography.scss
  source/_patterns/00-atoms/05-forms/_00-forms.scss
  source/_patterns/00-atoms/07-tables/_00-table.scss
  source/_patterns/00-atoms/07-tables/_google-table.scss
  source/_patterns/01-molecules/page_title_with_image/_page_title_with_image.scss
  source/_patterns/01-molecules/page_title_with_image/page_title_with_image.json
  source/_patterns/01-molecules/page_title_with_image/page_title_with_image.twig
  source/_patterns/01-molecules/teaser-promotion/_teaser-promotion.scss
  source/_patterns/01-molecules/text-card/_text-card.scss
  source/_patterns/01-molecules/text-card/_text-collection.scss
  source/_patterns/01-molecules/text-card/text-card.twig
  source/_patterns/01-molecules/user-settings/user-settings.js
  source/_patterns/02-organisms/navigation-minor/_navigation-minor.scss
  source/_patterns/02-organisms/text-card-collection/_text-card-collection.scss
  source/_patterns/02-organisms/text-card-collection/text-card-collection.twig
  source/_patterns/03-templates/00-layout/_layout-section.scss
  source/images/sample/independent_man_cropped.jpg
Labels: js, scss, twig
