Repository State-of-Rhode-Island-eCMS/ecms_patternlab, pull requests merged in 2020-10, with the labels that each got.

#6 Remove |render from column layouts
  .gitignore
  source/_patterns/01-molecules/01-layout/four-column.twig
  source/_patterns/01-molecules/01-layout/one-column.twig
  source/_patterns/01-molecules/01-layout/three-column.twig
  source/_patterns/01-molecules/01-layout/two-column.twig
Labels: approved, twig

#8 Color palette base work
  dist/css/pattern-lab-compiled.css
  gulpfile.js
  package-lock.json
  package.json
  source/_data/color-config.json
  source/_data/colors-generated.json
  source/_data/data.json
  source/_patterns/00-atoms/01-global/00-colors.twig
  source/_patterns/00-atoms/01-global/_00-colors.scss
  source/_patterns/00-atoms/02-text/01-paragraph.twig
  source/_patterns/02-organisms/00-global/_footer.scss
  source/_patterns/02-organisms/00-global/footer.twig
  source/_patterns/03-templates/00-layouts/html.html.twig
  source/_patterns/04-pages/00-homepage.twig
  source/_patterns/04-pages/_00-homepage-layout-STUB.scss
  source/_patterns/04-pages/_00-theme--blue.scss
  source/css/scss/admin/_index.scss
  source/css/scss/admin/_toolbar.scss
  source/css/style.scss
Labels: js, scss, twig

#9 Add gulp tasks to move a fonts and vendors folder to dist
  dist/fonts/icons.dev.svg
  dist/fonts/icons.eot
  dist/fonts/icons.svg
  dist/fonts/icons.ttf
  dist/fonts/icons.woff
  dist/fonts/roboto-slab-vf/RobotoSlab.woff2
  dist/fonts/work-sans-vf/WorkSans-Italic-subset.woff2
  dist/fonts/work-sans-vf/WorkSans-Roman-subset.woff2
  dist/js/pattern-lab-compiled-min.js
  dist/js/pattern-lab-compiled.js
  dist/vendor/fontfaceobserver.js
  gulpfile.js
  source/vendor/fontfaceobserver.js
Labels: js

#10 Prepare the changelog for 0.1.0
  CHANGELOG.md
Labels: approved, release

#13 Prepare changelog for 0.1.1 release.
  CHANGELOG.md
Labels: approved, release

#15 Prepare changelog for 0.1.2 release
  CHANGELOG.md
Labels: approved, release

#16 Video fixes, Federal Hill theme, Copyright bar, Layout tweaks, Front page links, and other updates
  dist/css/pattern-lab-compiled.css
  source/_data/color-config.json
  source/_data/colors-generated.json
  source/_data/data.json
  source/_patterns/00-atoms/00-base/__functions.scss
  source/_patterns/00-atoms/01-global/_00-colors.scss
  source/_patterns/00-atoms/01-global/_00-html.scss
  source/_patterns/00-atoms/02-text/00-links.twig
  source/_patterns/00-atoms/02-text/_00-links.scss
  source/_patterns/00-atoms/02-text/_00-typography.scss
  source/_patterns/00-atoms/04-images/04-avatar.twig
  source/_patterns/00-atoms/04-images/_00-images.scss
  source/_patterns/01-molecules/01-layout/_layout-section.scss
  source/_patterns/01-molecules/01-layout/four-column.twig
  source/_patterns/01-molecules/01-layout/one-column.twig
  source/_patterns/01-molecules/01-layout/three-column.twig
  source/_patterns/01-molecules/01-layout/two-column.twig
  source/_patterns/01-molecules/media-item/_media_item.scss
  source/_patterns/01-molecules/media-item/media-item.twig
  source/_patterns/01-molecules/media-item/media-item~video.json
  source/_patterns/01-molecules/site-branding/_site-branding.scss
  source/_patterns/01-molecules/site-branding/site-branding.twig
  source/_patterns/02-organisms/navigation-main/navigation-main.twig
  source/_patterns/02-organisms/page-footer/_page-footer.scss
  source/_patterns/02-organisms/page-footer/page-footer.json
  source/_patterns/02-organisms/page-footer/page-footer.twig
  source/_patterns/02-organisms/page-header/page-header.twig
  source/_patterns/02-organisms/paragraphs/accordion/_accordion.scss
  source/_patterns/02-organisms/paragraphs/attention-card-w-icon/_attention-card-w-icon.scss
  source/_patterns/02-organisms/paragraphs/attention-card-w-icon/attention-card-w-icon.twig
  source/_patterns/03-templates/00-layouts/page.html.pl.twig
  source/_patterns/03-templates/01-content/node--landing-page.pl.twig
  source/_patterns/04-pages/00-homepage.twig
  source/_patterns/04-pages/_00-homepage-layout-STUB.scss
  source/_patterns/04-pages/_00-theme--blue.scss
  source/images/icons/default-logo.svg
  source/images/icons/ri-state-seal.svg
Labels: js, scss, twig

#17 Start of dark mode support
  dist/css/pattern-lab-compiled.css
  source/_data/color-config.json
  source/_data/colors-generated.json
  source/_patterns/00-atoms/01-global/_00-colors.scss
  source/_patterns/00-atoms/01-global/_00-html.scss
  source/_patterns/00-atoms/01-global/_00-themes.scss
  source/_patterns/00-atoms/06-buttons/00-buttons.twig
  source/_patterns/00-atoms/06-buttons/_00-buttons.scss
  source/_patterns/01-molecules/sub-themes/sub-theme-test.twig
  source/_patterns/02-organisms/navigation-minor/_navigation-minor.scss
  source/_patterns/02-organisms/paragraphs/accordion/_accordion.scss
  source/_patterns/02-organisms/paragraphs/attention-card-w-icon/_attention-card-w-icon.scss
Labels: scss, twig

#18 Prepare changelog for 0.1.3 release
  CHANGELOG.md
Labels: approved, release

#21 Prepare changelog for 0.1.4 release
  CHANGELOG.md
Labels: approved, release

#22 Remove t function from file.twig
  CHANGELOG.md
  source/_patterns/01-molecules/file/file.twig
Labels: bug, twig

#23 Prepare changelog for 0.1.5
  CHANGELOG.md
Labels: approved, release
